version: '3.8'

services:
  fastapi:
    image: sriharim279/fastapi:dev  # replace with actual docker user id if needed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    image: sriharim279/streamlit:dev  # replace with actual docker user id if needed
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
