apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom # Match the label of your Prometheus instance as per Helm release
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default # or your specific namespace
  endpoints:
    - port: "8000" # Match the name of the port exposed by your service
      path: /metrics
      interval: 15s
